GET http://localhost:8080/professional 
# the request above returns a json object with all professional data for Nathan Birch. No database is connected.


GET https://cse341-restclients.onrender.com/localhost:8080/professional
# the request above returns a json object with all professional data for Nathan Birch. No database is connected.